# Generated by Django 3.1.4 on 2021-01-05 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20201229_1915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
