# Generated by Django 3.1.4 on 2021-01-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='public_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
