# Generated by Django 3.1.4 on 2021-01-06 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210105_0457'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
